modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved."

[[mods]]
    modId="classicui"
    version="1.0.0"
    displayName="ClassicUI"
    authors="FireControl1847"
    description="Bring back the UI from the good ol' days"

[[dependencies.classicui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="CLIENT"